# Generated by Django 2.2.18 on 2021-05-23 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('send_datetime', models.DateTimeField(default=datetime.datetime(2020, 8, 1, 0, 0))),
                ('send_to', models.CharField(choices=[('INFO', '정보성 메일'), ('AD', '광고성 메일'), ('NONE', '참가자에게 보내지 않음')], default='INFO', max_length=100)),
                ('send_to_newsletter_subscriber', models.CharField(choices=[('YES', '구독자에게 보내기'), ('NO', '구독자에게 보내지 않기')], default='NO', max_length=100)),
                ('send_successfully', models.BooleanField(default=False)),
                ('sender_name', models.CharField(default='PyCon Korea', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='소식을 받을 이메일 주소', max_length=254)),
                ('agree_coc', models.BooleanField(default=False, help_text='참가자 슬랙 초대용 CoC 동의 여부')),
            ],
        ),
    ]
