# Generated by Django 2.2.18 on 2021-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('title_ko', models.CharField(db_index=True, max_length=100, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=100, null=True)),
                ('url', models.URLField(help_text='공지 내용을 볼 수 있는 링크입니다. 주로 페이스북 공지 링크가 들어가게 됩니다.', max_length=500)),
                ('active', models.BooleanField(default=True, help_text='True면 공지사항이 노출됩니다.')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
