# Generated by Django 2.2.18 on 2021-05-23 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('name_ko', models.CharField(db_index=True, max_length=100, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='스프린트 제목', max_length=255)),
                ('brief', models.CharField(blank=True, help_text='스프린트에 대한 짧은 설명', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text='스프린트를 진행할 프로그래밍 언어', max_length=255, null=True)),
                ('url', models.CharField(blank=True, help_text='홈페이지에 공개되는 스프린트 관련 주소입니다.', max_length=255, null=True)),
                ('creator', models.ForeignKey(help_text='스프린트를 등록한 유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField(max_length=1000)),
                ('desc', models.TextField(max_length=4000)),
                ('comment', models.TextField(blank=True, max_length=4000, null=True)),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Experienced')], max_length=1)),
                ('duration', models.CharField(choices=[('S', '25min'), ('L', '40min')], max_length=1)),
                ('language', models.CharField(choices=[('', '---------'), ('K', 'Korean'), ('E', 'English')], default='', max_length=1)),
                ('accepted', models.BooleanField(default=False)),
                ('introduction', models.TextField(blank=True, help_text='발표 소개 페이지에 들어가는 내용입니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=1000, null=True)),
                ('video_url', models.CharField(blank=True, help_text='발표 영상 URL', max_length=255, null=True)),
                ('slide_url', models.CharField(blank=True, help_text='발표 자료 URL', max_length=255, null=True)),
                ('video_open_at', models.DateTimeField(blank=True, help_text='파이콘 한국 유튜브에 공개되는 시간', null=True)),
                ('track_num', models.IntegerField(blank=True, help_text='트랙 번호', null=True)),
                ('category', models.ForeignKey(blank=True, default=14, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='program.ProgramCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('submitted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.ProgramCategory')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightningTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='라이트닝 토크 제목', max_length=255)),
                ('slide_url', models.CharField(blank=True, max_length=511, null=True)),
                ('video_url', models.CharField(blank=True, max_length=511, null=True)),
                ('day', models.IntegerField(choices=[(1, '토요일'), (2, '일요일')])),
                ('brief', models.TextField(blank=True, help_text='라이트닝 토크 소개 문구', max_length=1000, null=True)),
                ('comment', models.TextField(blank=True, help_text='준비위원회에게 남기고 싶은 말', null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
