# Generated by Django 2.2.18 on 2021-05-23 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ko', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phrase', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=user.models.profile_image)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ko', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, help_text='여기에 기입한 조직 이름이 행사 당일 이름표에 표시됩니다.', max_length=100, null=True)),
                ('image_ori', sorl.thumbnail.fields.ImageField(blank=True, help_text='사용자 사진 원본', null=True, upload_to=user.models.profile_image)),
                ('image_small', sorl.thumbnail.fields.ImageField(blank=True, help_text='사용자 사진 축소본', null=True, upload_to=user.models.profile_image)),
                ('bio', models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True)),
                ('bio_ko', models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True)),
                ('bio_en', models.TextField(blank=True, help_text='이 내용이 개인 후원자 목록에 노출됩니다. 변경 사항은 최대 60분 이내에 적용됩니다.', max_length=4000, null=True)),
                ('user_code', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement_receive_advertising_info', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
